name: Deploy Node.js app to Vercel

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            # Tùy chọn: Tạo file zip
            # - name: Zip artifact for deployment
            #   run: zip -r release.zip .

            - name: Install Vercel CLI
              uses: vercel/toolchain@v0.33.2

            # Bỏ qua nếu đã đăng nhập Vercel CLI
            # - name: Login to Vercel (nếu cần)
            #   run: vercel login

            - name: Build and deploy
              run: vercel deploy
