name: Build and deploy Node.js app to Azure Web App - nkreative

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Tốt hơn là dùng 'ci' để cài đặt chính xác các dependencies

      - name: Build app
        run: npm run build # Thay thế bằng lệnh build cụ thể của bạn (ví dụ: npm run build, next build,...)

      - name: Zip artifact for deployment
        run: zip release.zip dist/* -r # Giả sử thư mục 'dist' là nơi chứa kết quả build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_051B48CD494D47E6ADEEC6104265F2F5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CEAD54F33E224DC48EC7A4E514BA39E7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22C5D5005C974393860B2D241DF86471 }}

      - name: Deploy to Azure Web App (Production Slot)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "nkreative"
          slot-name: "Production"
          package: "."
